### ISSUE TITLE
Releasing to hackage

### ISSUE THREAD

**Issue by begriffs** [alphaHeavy/consul-haskell#1]
Hey Steve, do you plan to release this to hackage any time soon? I'd like to use it in a project (the key value functionality in particular).

**Comment by sseveran** [comment]
Hi Joe, Yes I do. I need to get some more testing done first. Any particular subset of APIs you need?

**Comment by begriffs** [comment]
Really all I need is to retrieve values from a given key. I'm currently just using the HTTP package

``` haskell
rsp <- simpleHTTP (getRequest "http://127.0.0.1:8500/v1/kv/respondents")
payload <- decode . cs <$> getResponseBody rsp
```

and then extracting things from the json inside. It's not that bad really, but if your library is almost ready then I'd rather use something like that designed specially for consul.

**Comment by sseveran** [comment]
I wouldn't call it almost ready but please feel free to use it. I am not done locking down the interfaces yet so expect them to change.

**Comment by dysinger** [comment]
Would you push it to hackage as 0.1? I'm fine with breaking changes. It works right now. If you completely change it tomorrow, I'll just lock the version I'm using into place until I'm ready to move.

Not having it on hackage forces me to choose. I may chose not use your library or I may end up writing my own library.  Having it on hackage encourages people to use it and participate in your experiment.

**Comment by sseveran** [comment]
I will create on 0.1 release by tomorrow.

**Comment by dysinger** [comment]
You are the most awesome

**Comment by sseveran** [comment]
Released https://hackage.haskell.org/package/consul-haskell

**Comment by dysinger** [comment]
thanks!
