### ISSUE TITLE
Maintanining this library?

### ISSUE THREAD

**Issue by ketzacoatl** [alphaHeavy/consul-haskell#23]
Hello,

Thank you for your work creating and maintaining this library. There are a pending tasks/tickets and PRs piling up, so I'd like to ask: what are the project's plans for maintaining the library?

Would it make sense to put out a call for maintainers?

**Comment by ketzacoatl** [comment]
Ping, are the devs interested in this?

Alternatively, we could fork and carry on development there?

**Comment by nh2** [comment]
Hello @NathanHowell and @sseveran,

I'd be happy to help maintaining this package, or take over maintainership.

I'm [one of the maintainers of Consul in nixpkgs](https://github.com/nh2/nixpkgs/blob/9d17e5e77c6e82dfd2870c9d5c9f514bf472b07e/pkgs/servers/consul/default.nix#L34), and use it for various tasks. I also work with @ketzacoatl and other people who depend on Consul.

I'm currently using the [version in my fork](https://github.com/alphaHeavy/consul-haskell/compare/master...nh2:nh2fixes) that also fixes [Consul 1.0 compatibility](https://github.com/alphaHeavy/consul-haskell/commit/da899d006e93d76748a75e017f77a8f49f9871d2).

Let me know!

**Comment by NathanHowell** [comment]
That would be great. I'll add you as contributors this weekend, assuming
Steve is cool with it.

thx

**Comment by NathanHowell** [comment]
Commit bit granted, please coordinate with @sseveran for Hackage permissions if needed

**Comment by ketzacoatl** [comment]
Thanks!

**Comment by nh2** [comment]
@NathanHowell @sseveran Thanks, that's great!

Hackage access would be nice, https://hackage.haskell.org/user/NiklasHambuechen on Hackage.

To what extent do you still want to participate in development? Should we CC you on certain changes, do you have production deployments of old versions of Consul or GHCs that we should take care to stay compatible with, anything of that sort?

**Comment by sseveran** [comment]
I will figure out how to get you hackage access. You should take the library in whatever direction you want. No need to CC us on anything. We use a pinned commit in stack so you won't effect us.

**Comment by sseveran** [comment]
@nh2 Do you know how I can give you access on Hackage?

**Comment by nh2** [comment]
> Do you know how I can give you access on Hackage?

@sseveran Yes, go to https://hackage.haskell.org/package/consul-haskell/maintainers/ and click `Edit`.

**Comment by sseveran** [comment]
@nh2 Done.
