### ISSUE TITLE
Tests race condition: Sometimes consul does not respond even though the port is open 

### ISSUE THREAD

**Issue by nh2** [alphaHeavy/consul-haskell#30]
In https://github.com/alphaHeavy/consul-haskell/blob/4a9151ce8ee00fb59f37ed33ee4b32892800c10d/tests/Main.hs#L392-L401

I wait for Consul's port to be open before making requests to avoid race conditions between our tests and Consul not being ready.

Turns out this isn't enough, there is a time after which Consul will have opened the port but is still not ready. Evidenced by tests sometimes failing with `http: Request PUT /v1/session/create, error: Missing node registration`:

```
  Internal Session Tests
    testCreateSession:               2020/01/20 17:09:30 [ERR] http: Request PUT /v1/session/create, error: Missing node registration from=127.0.0.1:51866
FAIL
      tests/Main.hs:237:
      testCreateSession: No session was created
    testGetSessionInfo:              2020/01/20 17:09:30 [ERR] http: Request PUT /v1/session/create, error: Missing node registration from=127.0.0.1:51870
FAIL
      tests/Main.hs:250:
      testGetSessionInfo: No session was created
    testRenewSession:                2020/01/20 17:09:30 [ERR] http: Request PUT /v1/session/create, error: Missing node registration from=127.0.0.1:51874
FAIL
      tests/Main.hs:263:
      testRenewSession: No session was created
    testRenewNonexistentSession: OK
    testDestroySession:          OK
```

Very annoying; we'll have to have a more sophisticated check for Consul being ready.

**Comment by ketzacoatl** [comment]
Yes, in this case, we could say consul has several "I'm up and ready for work" stages:
1) consul is listening on the HTTP port
2) HTTP interface is up / consul agent is ready
3) consul agent has joined the cluster / confirmed cluster leadership (or has acquired leadership if in dev mode?)

I've used "the ability to create a session" as "my local consul agent is healthy and has joined the cluster". In this case, we could probably use "HTTP interface is up / consul agent is ready", which ought to be as soon as the basic status HTTP API/interface returns a 200.

**Comment by ketzacoatl** [comment]
We address this in https://github.com/alphaHeavy/consul-haskell/pull/45, and I believe this is now good to close.
